# LAB 01.01 - Practice submission

### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     
_Sugerencia_: completa el código de la siguiente manera:

    def suma_matrices(a,b):
       ## --- TU CODIGO AQUI ---
       result = a + b
       return result

In [3]:

def suma_matrices(a,b):
    ## --- TU CODIGO AQUI ---
    result = a + b 
    return result



comprueba manualmente tu código

In [4]:
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print (a)
print (b)
print (suma_matrices(a,b))

[[8 0]
 [8 0]
 [0 6]]
[[9 4]
 [0 6]
 [2 1]]
[[17  4]
 [ 8  6]
 [ 2  7]]


### Ejercicio 2: Realiza un cálculo 

En este ejercicio, al ejecutar la celda de más abajo, se generará una lista de número aleatorios.

Tendrás que calcular el valor promedio de la lista y asignarlo a la variable `avg` más abajo.

Puedes usar el método que quieras para realizar el cálculo (a mano, excel, python, etc.) lo que importa es el valor que obtengas.


In [6]:
import numpy as np
rlist = np.random.randint(100, size=10)
rlist

array([66, 68, 79, 68, 34, 55, 45, 22, 33, 73])

#### tu solución

In [7]:
avg = np.mean(rlist)

In [9]:
sum(rlist)/len(rlist)

54.3

In [8]:
avg

54.3