# LAB 02.04 - Card trick

In [1]:
import numpy as np
import pandas as pd
import itertools

## Setup 

make sure to **watch the corresponding video** to understand the card trick.

### create a deck for a given configuration

The following function returns a list of **card names**. The `shuffle` argument is self evident. We use two letters as an arbitrary card name so that we have enough names for large configurations.

In [171]:
def create_deck(n_heaps, cards_per_heap, shuffle=False):
    n_cards = n_heaps * cards_per_heap
    
    chars = [chr(i) for i in np.arange(26)+65]
    names = [i+j for i,j in itertools.product(chars, chars)]    

    assert n_cards < len(names), "cannot have more than %d cards"%len(names)
    
    c = np.r_[names[:n_cards]]
    if shuffle:
        c = np.random.permutation(c)
    return c

In [4]:
len(create_deck(n_heaps=3, cards_per_heap=10, shuffle=False))

30

In [11]:
create_deck(n_heaps=3, cards_per_heap=10, shuffle=False).reshape(3,-1)

array([['AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI', 'AJ'],
       ['AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR', 'AS', 'AT'],
       ['AU', 'AV', 'AW', 'AX', 'AY', 'AZ', 'BA', 'BB', 'BC', 'BD']],
      dtype='<U2')

In [5]:
create_deck(n_heaps=3, cards_per_heap=7, shuffle=True)

array(['AD', 'AH', 'AN', 'AI', 'AJ', 'AE', 'AG', 'AF', 'AO', 'AR', 'AC',
       'AA', 'AT', 'AL', 'AB', 'AS', 'AP', 'AQ', 'AU', 'AM', 'AK'],
      dtype='<U2')

In [6]:
len(create_deck(n_heaps=3, cards_per_heap=7, shuffle=True))

21

In [ ]:
create_deck(n_heaps=3, cards_per_heap=10, shuffle=True)

array(['AC', 'AQ', 'AW', 'AG', 'AK', 'AB', 'BB', 'AF', 'AU', 'AS', 'AA',
       'AX', 'AZ', 'AY', 'BD', 'AV', 'AI', 'AE', 'AR', 'AJ', 'AH', 'AN',
       'AL', 'BC', 'AM', 'BA', 'AO', 'AP', 'AT', 'AD'], dtype='<U2')

### pick a card

the following function randomly picks a card from a deck

In [10]:
def pick_card(c):
    return np.random.choice(c)

In [ ]:
c = create_deck(n_heaps=3, cards_per_heap=7, shuffle=True)
n = pick_card(c)
n

'AC'

## Task 1. Make the heaps

Complete the following funcion so that given desk (as a list returned by `create_deck`) distributes the cards in `n_heaps` according to the procedure of the card trick shown in the video.

The heaps must be a list of `n_heaps` lists, each one with `len(c)/n_heaps` card names.

`n_heaps` will be an odd number (so that later we can put the chosen heap in the middle of the others), and must be a divisor of the total number of cards in the deck (so that all heaps have the same number of cards)

For instance, 

    >>> n_heaps = 3
    >>> c = create_deck(n_heaps=n_heaps, cards_per_heap=7)
    >>> h = make_heaps(c, n_heaps)
    >>> print("deck", c)
    >>> print("heaps")
    >>> h   

    deck ['AA' 'AB' 'AC' 'AD' 'AE' 'AF' 'AG' 'AH' 'AI' 'AJ' 'AK' 'AL' 'AM' 'AN'
     'AO' 'AP' 'AQ' 'AR' 'AS' 'AT' 'AU']
    heaps
    [['AA', 'AD', 'AG', 'AJ', 'AM', 'AP', 'AS'],
     ['AB', 'AE', 'AH', 'AK', 'AN', 'AQ', 'AT'],
     ['AC', 'AF', 'AI', 'AL', 'AO', 'AR', 'AU']]
  
or also

    >>> n_heaps = 5
    >>> c = create_deck(n_heaps=n_heaps, cards_per_heap=3, shuffle=True)
    >>> h = make_heaps(c, n_heaps)
    >>> print("deck", c)
    >>> print("heaps")
    >>> h
    
    deck ['AA' 'AJ' 'AM' 'AK' 'AH' 'AF' 'AD' 'AN' 'AB' 'AC' 'AG' 'AE' 'AL' 'AI'
     'AO']
    heaps
    [['AA', 'AF', 'AG'],
     ['AJ', 'AD', 'AE'],
     ['AM', 'AN', 'AL'],
     ['AK', 'AB', 'AI'],
     ['AH', 'AC', 'AO']]

In [393]:
def make_heaps(c, n_heaps=3):
    assert n_heaps%2==1, "must have an odd number of heaps"
    assert len(c)%n_heaps==0, "the length of the deck must be a multiple of the number of heaps"
    
    h = np.asarray(c).reshape(-1, n_heaps).T.tolist()
    return h

manually check your code

In [394]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=7)
h = make_heaps(c, n_heaps)

print("deck", c)
print("heaps")
h


deck ['AA' 'AB' 'AC' 'AD' 'AE' 'AF' 'AG' 'AH' 'AI' 'AJ' 'AK' 'AL' 'AM' 'AN'
 'AO' 'AP' 'AQ' 'AR' 'AS' 'AT' 'AU']
heaps


[['AA', 'AD', 'AG', 'AJ', 'AM', 'AP', 'AS'],
 ['AB', 'AE', 'AH', 'AK', 'AN', 'AQ', 'AT'],
 ['AC', 'AF', 'AI', 'AL', 'AO', 'AR', 'AU']]

In [395]:
type(h)

list

In [194]:
n_heaps = 5
c = create_deck(n_heaps=n_heaps, cards_per_heap=3, shuffle=True)
h = make_heaps(c, n_heaps)

print("deck", c)
print("heaps\n")
h


deck ['AK' 'AI' 'AN' 'AD' 'AL' 'AB' 'AC' 'AG' 'AE' 'AO' 'AH' 'AF' 'AA' 'AJ'
 'AM']
heaps



[['AK', 'AB', 'AH'],
 ['AI', 'AC', 'AF'],
 ['AN', 'AG', 'AA'],
 ['AD', 'AE', 'AJ'],
 ['AL', 'AO', 'AM']]

In [191]:
n = pick_card(c)
n

'AI'

In [150]:
new_h = np.random.permutation(h.copy())
new_h

array([['AL', 'AA', 'AG'],
       ['AD', 'AC', 'AM'],
       ['AJ', 'AI', 'AF'],
       ['AN', 'AB', 'AO'],
       ['AE', 'AK', 'AH']], dtype='<U2')

In [151]:
h_with_n_index = np.where(new_h == n)[0][0]
h_with_n_index

3

In [152]:
middle_of_h = len(new_h)//2
middle_of_h

2

In [153]:
old_middle_h = new_h[middle_of_h].copy()
new_h[middle_of_h] = new_h[h_with_n_index]
new_h[h_with_n_index] = old_middle_h

In [154]:
new_h

array([['AL', 'AA', 'AG'],
       ['AD', 'AC', 'AM'],
       ['AN', 'AB', 'AO'],
       ['AJ', 'AI', 'AF'],
       ['AE', 'AK', 'AH']], dtype='<U2')

## Task 2: Organize the heaps

Complete the following funcion so that given a set of heaps (such as the ones returned by the function of the previous task) and a card name:

1. Finds what is the heap that contains the card
1. Makes randomly two groups of `n_heaps//2` heaps of the remaining heaps
   - if `n_heaps=3` this will be two groups of one heap each, since `3//2=1`
   - if `n_heaps=5`, it will be two groups of two heaps each, since `5//2=2`
   - etc. (observe `//` is the integer division)
1. Concatenates the cards in one group with the cards in the heap containing the given card name. with the cards of the second group

For example

    >>> n_heaps = 3
    >>> c = create_deck(n_heaps=n_heaps, cards_per_heap=7, shuffle=True)
    >>> n = pick_card(c)
    >>> print ("card picked", n)
    >>> h = make_heaps(c, n_heaps)
    >>> h
    
    card picked AD
    [['AP', 'AC', 'AE', 'AO', 'AQ', 'AF', 'AM'],
     ['AN', 'AT', 'AB', 'AJ', 'AU', 'AI', 'AS'],
     ['AR', 'AD', 'AA', 'AG', 'AH', 'AL', 'AK']]
    
    
    >>> new_c = collect_heaps(h, n)
    >>> print (new_c)
    
    ['AP', 'AC', 'AE', 'AO', 'AQ', 'AF', 'AM', 'AR', 'AD', 'AA', 'AG', 'AH', 'AL', 'AK', 'AN', 'AT', 'AB', 'AJ', 'AU', 'AI', 'AS']

In [390]:
def collect_heaps(h, n):
    new_h = np.copy(h)
    new_h = np.random.permutation(new_h)
    h_with_n_index = np.where(new_h == n)[0][0]
    middle_of_h = len(new_h)//2

    old_middle_h = new_h[middle_of_h].copy()
    new_h[middle_of_h] = new_h[h_with_n_index]
    new_h[h_with_n_index] = old_middle_h
    
    return new_h.ravel().tolist()     

manually check your code

In [224]:
n_heaps = 5
c = create_deck(n_heaps=n_heaps, cards_per_heap=7, shuffle=True)
n = pick_card(c)
print ("card picked", n)
h = make_heaps(c, n_heaps)
h

card picked BE


[['BF', 'AJ', 'AS', 'AB', 'AI', 'BH', 'AZ'],
 ['AD', 'AW', 'AC', 'AV', 'AK', 'BE', 'AF'],
 ['BI', 'AX', 'AG', 'BB', 'AU', 'AN', 'AO'],
 ['BA', 'BD', 'BC', 'AM', 'AE', 'AQ', 'AL'],
 ['AY', 'BG', 'AH', 'AA', 'AT', 'AP', 'AR']]

In [228]:
new_c = collect_heaps(h, n)
new_c.index(n)

19

## Task 3: Run the card trick

Complete the following function such that, when given a a deck of cards `c`, and picked card `n` and a number of heaps `n_heaps`, returns the position of the picked card after doing three times the collect. The position number **must start at zero**.

For instance:

- For `n_heaps=3` and `cards_per_heap=7`, the final position will always be 10 (which is 11 if you start counting at 1)
- For `n_heaps=3` and `cards_per_heap=4`, the final position will be sometimes 5 and sometimes 6 depending on the position of the picked card on the initial deck.
- For `n_heaps=5` and `cards_per_heap=3`, the final position will always be 7

**You must return an `int`**

In [484]:
def run(c, n, n_heaps=3):    
 
    for i in range(3):
      c = collect_heaps(make_heaps(c, n_heaps), n)

    r = c.index(n)
    return r

In [385]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=7)
picked = "AA"
print ("desk", c)

desk ['AA' 'AB' 'AC' 'AD' 'AE' 'AF' 'AG' 'AH' 'AI' 'AJ' 'AK' 'AL' 'AM' 'AN'
 'AO' 'AP' 'AQ' 'AR' 'AS' 'AT' 'AU']


manually check your code

In [478]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=7)
picked = "AA"
print ("desk", c)
pos = run(c, picked, n_heaps=n_heaps)
print ("position of card %s is %d"%(picked, pos))

desk ['AA' 'AB' 'AC' 'AD' 'AE' 'AF' 'AG' 'AH' 'AI' 'AJ' 'AK' 'AL' 'AM' 'AN'
 'AO' 'AP' 'AQ' 'AR' 'AS' 'AT' 'AU']
position of card AA is 9


In [471]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=4)
picked = "AB"
print ("deck", c)

pos = run(c, picked, n_heaps=n_heaps)
print ("position of card %s is %d"%(picked, pos))

deck ['AA' 'AB' 'AC' 'AD' 'AE' 'AF' 'AG' 'AH' 'AI' 'AJ' 'AK' 'AL']
position of card AB is 5


In [467]:
n_heaps = 5
c = create_deck(n_heaps=n_heaps, cards_per_heap=3)
picked = "AI"
print ("deck", c)
pos = run(c, picked, n_heaps=n_heaps)
print ("position of card %s is %d"%(picked, pos))

deck ['AA' 'AB' 'AC' 'AD' 'AE' 'AF' 'AG' 'AH' 'AI' 'AJ' 'AK' 'AL' 'AM' 'AN'
 'AO']
position of card AI is 7


In [503]:
POS = []
n_heaps = 3
for i in range(100):
  c = create_deck(n_heaps=n_heaps, cards_per_heap=4, shuffle=True)
  picked = pick_card(c)
  #print ("deck", c)
  #print ("card picked", picked)

  pos = run(c, picked, n_heaps=n_heaps)
  #print ("position of card %s is %d"%(picked, pos))
  POS.append(pos)
np.unique(POS)

array([5, 6])

array([6])

In [252]:
c = ['BV', 'BO', 'BS', 'BH', 'BA', 'BE', 'AE', 'BQ', 'CA', 'BK', 'AJ', 'BC', 'CB', 'AK',
     'AR', 'AN', 'AG', 'AH', 'BM', 'BU', 'BY', 'AM', 'AF', 'CD', 'AW', 'AA', 'BF', 'AY',
     'BB', 'BP', 'BG', 'BN', 'AO', 'BD', 'AL', 'AX', 'AT', 'AC', 'AB', 'BJ', 'AS', 'BI',
     'BX', 'AQ', 'BZ', 'AU', 'AD', 'BW', 'BR', 'AI', 'AV', 'BL', 'AP', 'CC', 'AZ', 'BT']


In [253]:
len(c)

56

54

## Task 4: Run the trick using the math

Given:

- $n_h$: A number of heaps
- $c_h$: the number of cards per heap
- $i$: the position of a card 

The new position of the card after one cycle of making and collecting the heaps will be:

$$c_h(n_h\div2)+i\div n_h$$

Complete the following function so that it has the same functionality of the previous task, but applying only this formula without using the simulation above. You **MUST NOT ADD** or remove lines from the function skeleton below, **ONLY** fill in the `...`

You must get the same results as the previous task.

**HINT**: Use `np.argwhere` to get the initial position of the card in the deck

In [505]:
def mrun(c, picked_card, n_heaps=3):
    assert len(c)%n_heaps==0, "the number of heaps must be a divisor of the deck length"
    
    ch = len(c)//n_heaps # cards per heap
    nh = n_heaps
    
    i = np.argwhere(c == picked_card)[0][0] # initial position of the card on the deck c
    p1 = ch*(nh//2) + (i//nh)  # the position of the card after the first round
    p2 = ch*(nh//2) + (p1//nh) # the position of the card after the second round
    p3 = ch*(nh//2) + (p2//nh) # the position of the card after the last round
    
    return p3

In [496]:
n_heaps = 3
picked = "AI"

c = create_deck(n_heaps=n_heaps, cards_per_heap=4)
np.argwhere(c == picked)

array([[8]])

In [508]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=4)
picked = "AI"
print ("deck", c)

pos = mrun(c, picked, n_heaps=n_heaps)
print ("position of card %s is %d"%(picked, pos))

deck ['AA' 'AB' 'AC' 'AD' 'AE' 'AF' 'AG' 'AH' 'AI' 'AJ' 'AK' 'AL']
position of card AI is 6


**submit your code**

## You are done. Now, some considerations

### using the math is always faster!!!



In [ ]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=4)
picked = "AI"
print ("deck", c)

In [ ]:
%timeit run(c, picked, n_heaps=n_heaps)

In [ ]:
%timeit mrun(c, picked, n_heaps=n_heaps)

### you can check if the trick works for a specific configuration

In [ ]:
n_heaps = 3
cards_per_heap = 7

c = create_deck(n_heaps, cards_per_heap)

r = [[n, mrun(c,n, n_heaps=n_heaps)] for n in c]
print ("deck", c)
pd.DataFrame(r, columns=["card picked", "final position"])

In [ ]:
n_heaps = 3
cards_per_heap = 4

c = create_deck(n_heaps, cards_per_heap)

r = [[n, mrun(c,n, n_heaps=n_heaps)] for n in c]
print ("deck", c)
pd.DataFrame(r, columns=["card picked", "final position"])